version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./resources/Data.sql:/docker-entrypoint-initdb.d/Data.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

volumes:
  container-volume:
